### ISSUE TITLE
Could the scenario of Predator-Prey be also released?

### ISSUE THREAD

**Issue by YeTianJHU** [uoe-agents/LIAM#1]
Thanks for releasing the code. I noticed that the reward setting of the Predator-Prey in the paper is different from the simple_tag of the particle environment. It would be great if the author could also share the paper version of the scenario.

Thanks,
Ye

**Comment by papoudakis** [comment]
Hi,
we will upload the code in the next 2-3 weeks. I will close the issue once the code has been uploaded.
Best,
Georgios

**Comment by YeTianJHU** [comment]
Hi Georgios,
May I know if there are any update about the releasing of the Predator-Prey part of the code? Great thanks!
Best,
Ye

**Comment by papoudakis** [comment]
Hi Ye,
sorry for the delay. It has been added now.
Best
Georgios

**Comment by YeTianJHU** [comment]
Thanks Georgios! It looks great.

I'll close the issue then.

Best,
Ye
