### ISSUE TITLE
Is LIAM a single-agent RL method?

### ISSUE THREAD

**Issue by GoingMyWay** [uoe-agents/LIAM#2]
Dear Authors,

Thanks for sharing the awesome code of LIAM. After reading your paper and the code, I found LIAM is actually a single-agent RL method with pre-trained models of other agents in multi-agent environments. Please correct me if I am not right. 

I found there are codes for evaluation. By the way, will you share the code for training the models, for example, the models of DDPG agents?

**Comment by papoudakis** [comment]
Hi,
LIAM is indeed a single-agent RL method. 
To create the pre-trained models we trained pairs of agents using the MADDPG algorithm from this repo: https://github.com/shariqiqbal2810/maddpg-pytorch

**Comment by GoingMyWay** [comment]
> Hi, LIAM is indeed a single-agent RL method. To create the pre-trained models we trained pairs of agents using the MADDPG algorithm from this repo: https://github.com/shariqiqbal2810/maddpg-pytorch

Dear Author, thanks for sharing.
